apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: NodePort
  ports:
    - name: pms
      port: 32400
      protocol: TCP
      targetPort: pms
      nodePort: 32400
    - name: http
      port: 80
      targetPort: pms
    - name: https
      port: 443
      targetPort: 32443
  selector:
    app: {{ .Values.name }}
