
name: rclone

image:
  repository: rclone/rclone
  tag: latest
  pullPolicy: IfNotPresent


rclone:
  secretname: rclone-secret
  remote: "gcache:"
  path: /mnt/disks/gdrive
  readOnly: true
  additionalArgs:
    - --log-level=INFO
    # - --buffer-size=1G
    # - --dir-cache-time=72h
    # - --drive-chunk-size=256M
    # - --fast-list
    # - --vfs-read-chunk-size=128M
    # - --vfs-read-chunk-size-limit=off
    # - --drive-acknowledge-abuse=true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 250m
  #   memory: 1Gi
  # limits:
  #   cpu: 350m
  #   memory: 2Gi

nodeSelector: {}
