apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
          - mount
          - "{{ .Values.rclone.remote }}"
          - {{ .Values.rclone.path }}
          - --config=/etc/rclone/rclone.conf
          - --allow-non-empty
          - --allow-other
        {{- if .Values.rclone.readOnly }}
          - --read-only
        {{ end }}
        {{- range .Values.rclone.additionalArgs }}
          - {{ . }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","fusermount -uz {{ .Values.rclone.path }}"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/rclone
        - name: data
          mountPath: /var/lib/rclone
        - name: media
          mountPath: {{ .Values.rclone.path }}
          mountPropagation: Bidirectional
      volumes:
      - name: config
        secret:
          secretName: {{ .Values.rclone.secretname }}
      - name: media
        hostPath:
          path: {{ .Values.rclone.path }}
      - name: data
        hostPath:
          path: /var/lib/rclone/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
